[[subject_rules]]
pattern = "(?i)Price alert:"
description = "Coinbase price alerts"
folder = "INBOX/Notifications/Trades"

[[sender_rules]]
pattern = "(?i)^no[-_]?reply@.*"
description = "Automated emails"
folder = "INBOX/Notifications"

[[sender_rules]]
pattern = "(?i)email.nextdoor.com"
description = "Nextdoor emails"
folder = "INBOX/Promotions"

[[sender_rules]]
pattern = "(?i)notifications-noreply@linkedin.com"
description = "Linkedin Emails"
folder = "INBOX/Notifications"

[[sender_rules]]
pattern = "(?i)serasa@novidades.serasa.com.br"
description = "serasa"
folder = "INBOX/Promotions"

[[sender_rules]]
pattern = "(?i)support@e.usa.experian.com"
description = "Experian"
folder = "INBOX/Documents"

[[sender_rules]]
pattern = "(?i)bingo@patreon.com"
description = "Maverick"
folder = "INBOX/Documents/Payments"

[[sender_rules]]
pattern = "(?i)store-news@amazon.com"
description = "Amazon"
folder = "INBOX/Promotions"

[[sender_rules]]
pattern = "(?i)noreply@tradingview.com"
description = "TradingView"
folder = "INBOX/Notifications/Trades"

[[sender_rules]]
pattern = "(?i)hello@ohmconnect.com"
description = "OhmConnect"
folder = "INBOX/Documents/Bills"

[[sender_rules]]
pattern = "(?i)vbs@transactional.vanguard.com"
description = "Vanguard transactions"
folder = "INBOX/Notifications/Trades"

[[sender_rules]]
pattern = "(?i)email@washingtonpost.com"
description = "The Washington Post"
folder = "INBOX/News"

[[sender_rules]]
pattern = "(?i)auto-reply@usps.com"
description = "USPS"
folder = "INBOX/Notifications"

[[sender_rules]]
pattern = "(?i)DoNotReply@billpay.pge.com"
description = "PG&E"
folder = "INBOX/Documents/Bills"

[[sender_rules]]
pattern = "(?i)update@emailff.att-mail.com"
description = "ATT"
folder = "INBOX/Documents/Bills"

[[sender_rules]]
pattern = "(?i)no_reply@bayareafastrak.org"
description = "Fasttrack"
folder = "INBOX/Documents/Bills"

[[sender_rules]]
pattern = "(?i)noreply@paymentcenter.ebmud.com"
description = "EBMUD"
folder = "INBOX/Documents/Bills"

[[sender_rules]]
pattern = "(?i)no_reply@email.apple.com"
description = "Apple"
folder = "INBOX/Documents/Bills"

[[sender_rules]]
pattern = "(?i)purchase"
description = "Random purchases"
folder = "INBOX/Documents/Bills"

[[sender_rules]]
pattern = "(?i)@calottery.com"
description = "California Lottery Promotions"
folder = "INBOX/Promotions"

[[subject_rules]]
pattern = "(?i)\\b(Lottery|Jackpot|Winner|Promotion|Claim|Cash Prize)\\b"
description = "Lottery-related subjects"
folder = "INBOX/Promotions"

# AI prompt configuration
ai_prompt = """
You are an email classifier. Your task is to assign emails to EXISTING folders.

AVAILABLE FOLDERS: {folders_list}
DEFAULT FOLDER: {default_target_folder}

INSTRUCTIONS:
1. Select ONE folder from the list above - use EXACT spelling and path
2. If uncertain, use the DEFAULT FOLDER
3. Provide a brief reason

CLASSIFICATION GUIDELINES:
Primary Categories:
- INBOX: Personal emails from real people requiring attention
- INBOX/Promotions: Marketing emails, sales announcements, special offers
- INBOX/Documents: General documentation that doesn't fit specific subcategories
  - Documents/Orders: Purchase confirmations, receipts, shipping notifications
  - Documents/Bills: Bills, invoices, payment reminders
  - Documents/Payments: Payment confirmations, transaction receipts
  - Documents/Bank: Banking statements, account notifications
  - Documents/Tax: Tax-related documents
  - Documents/Car: Vehicle-related documentation
  - Documents/Company: Business and company-related documents

Notifications and News:
- INBOX/Notifications: General system notifications and automated messages
  - Notifications/Trades: Stock trades, investment alerts, financial transactions
  - Notifications/TrueNAS: Specific TrueNAS system alerts only
- INBOX/News: News articles, industry updates, press releases
- INBOX/Triage: Emails requiring review but not immediate attention

Lists: (Only for specific mailing list emails - check List-ID header)
- Lists/*: Technical mailing lists (e.g., Lists/Docker-User, Lists/Git)
  - Use specific subfolders for recognized mailing lists
  - Must have proper List-ID header

Special Purpose:
- INBOX/Cash: Financial opportunities or cash-related matters
- AIUnsure: When classification confidence is low
- Archive: Long-term storage for processed emails
- Later: Emails to be processed at a future time
- Newsletters: Regular newsletter subscriptions
- Purchases: General purchase-related emails not fitting in Documents/Orders
- Registrations: Account registrations and sign-ups
- Uncategorized: Default for emails that don't clearly fit elsewhere

Response format (JSON only):
{
    "target_folder": "EXACT_FOLDER_NAME",
    "reason": "Brief explanation"
}
"""

server = "imap.fastmail.com"
username = "user@fastmail.com"
target_folder = "INBOX/Newsletters"
use_hybrid = true
